import { Router } from 'express';
import { requireStaff, requireApp } from '../../middleware/admin.js';
import { APPS } from '@khalyx/shared';
import dashboard from './dashboard.js';
import products from './products.js';
import orders from './orders.js';
import customers from './customers.js';
import inventory from './inventory.js';
import coupons from './coupons.js';
import staff from './staff.js';
import reports from './reports.js';
import labels from './labels.js';
import uploads from './uploads.js';
import settings from './settings.js';
import suppliers from './suppliers.js';
import notifications from './notifications.js';
import search from './search.js';

const router = Router();
router.use(...requireStaff, requireApp(APPS.ADMIN));
router.use('/dashboard', dashboard);
router.use('/products', products);
router.use('/orders', orders);
router.use('/customers', customers);
router.use('/inventory', inventory);
router.use('/coupons', coupons);
router.use('/staff', staff);
router.use('/reports', reports);
router.use('/labels', labels);
router.use('/uploads', uploads);
router.use('/settings', settings);
router.use('/suppliers', suppliers);
router.use('/notifications', notifications);
router.use('/search', search);

export default router;
